#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 01 21:35:46 EEST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=PotatoShaders_v1.0d.zip
enableShaders=false
